modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/AdditionalBanners/issues"
license="LGPL v2.1"

[[mods]]
modId="additionalbanners"
updateJSONURL="https://updates.blamejared.com/get?n=additionalbanners&gv=1.16.4"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.additionalbanners]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.additionalbanners]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.additionalbanners]]
    modId="bookshelf"
    mandatory=true
    versionRange="[9,)"
    ordering="NONE"
    side="BOTH"